ecom_store/cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('success/', success, name='success'),
    path('checkout/', checkout, name='checkout'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('update_cart/<int:product_id>/<str:action>/', update_cart, name='update_cart'),
    path('hx_menu_cart/', hx_menu_cart, name='hx_menu_cart'),
    path('hx_cart_total/', hx_cart_total, name='hx_cart_total'),
]

ecom_store/ecom_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #cores
    path('', include('core.urls')),
    #cart
    path('cart/', include('cart.urls')),
    #order
    path('order/', include('order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom_store/product/urls.py
from django.urls import path
from .views import *

app_name = 'product'

urlpatterns = [
    path('', product, name='product')
]

ecom_store/product/models.py
from django.db import models
from django.core.files import File
from io import BytesIO
from PIL import Image
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'
        ordering = ('name', )

    def __str__(self):
        return self.name
    
    def total_items(self):
        return len(self.product.all())
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    description = models.TextField(blank=True, null=True)
    price = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='uploads/', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Товары'
        verbose_name = 'Товар'
        ordering = ('-created_at', )

    def __str__(self):
        return self.name
    
    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            return 'https://placehold.co/240x240'
    
    def make_thumbnail(self, image, size=(300, 300)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)

        thumb_io = BytesIO()
        img.save(thumb_io, 'JPEG', quality=85)

        thumbnail = File(thumb_io, name=image.name)
        return thumbnail
    
    def get_rating(self):
        reviews_total = 0
        for rev in self.reviews.all():
            reviews_total += rev.rating

        if reviews_total:
            return reviews_total / self.reviews.count()
        
        return 0
    
class Review(models.Model):
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE)
    rating = models.IntegerField(default=3)
    content = models.TextField()
    created_by = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Отзывы'
        verbose_name = 'Отзыв'

        

ecom_store/product/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Review

def product(request, slug):
    product = get_object_or_404(Product, slug=slug)
    if request.method == 'POST':
        rating = request.POST.get('rating', 3)
        content = request.POST.get('content', '')

        if content:
            reviews = Review.objects.filter(created_by=request.user, product=product)
            if reviews.count() > 0:
                review = reviews.first()
                review.rating = rating
                review.content = content
                review.save()
            else:
                review = Review.objects.create(
                    product=product,
                    rating=rating,
                    content=content,
                    created_by=request.user
                )
            
            return redirect('core:product', slug=slug)
    return render(request, 'product/product.html', {'product': product})

ecom_store/templates/product/product.html
{% extends 'core/base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}

<div class="max-w-6xl mx-auto flex flex-wrap py-6 px-6 xl:px-0">
    <div class="images w-full mb-6 lg:mb-0 lg:w-3/5">
        <img 
            class="rounded-xl" 
            src="{% if product.image %}
                    {{ product.image.url }}
                {% else %}
                    https://placehold.co/240x240
                {% endif %}">
    </div>

    <div class="information w-full lg:w-2/5 lg:p-6">
        <h1 class="text-2xl">{{ product.name }}</h1>
        <p class="mt-1 text-gray-400">{{ product.price }} руб.</p>
        {% if product.get_rating > 0 %}
            <p class="mt-1 text-gray-400">Рейтинг: {{ product.get_rating|floatformat }} / 5</p>
        {% endif %}
        {% if product.description %}
            <p class="mt-6 text-gray-700">{{ product.description }}</p>
        {% else %}
            <p class="mt-6 text-gray-700">Описание отсутствует</p>
        {% endif %}

        <a href="" class="mt-6 inline-block px-4 py-3 rounded-xl bg-purple-500 text-white hover:bg-purple-700" 
            hx-get="{% url 'cart:add_to_cart' product.id %}"
            hx-target="#menu-cart-button"
            hx-swap="outerHTML">В корзину
        </a>
    </div>
    <div class="w-full mt-6">
        <h2 class="text-xl">Отзывы</h2>

        {% if request.user.is_authenticated %}
            <form method="post" class="mt-6 mb-6 p-6 bg-gray-100 rounded-xl">
                {% csrf_token %}
                <div>
                    <label>Рейтинг</label><br>
                    <select name="rating">
                        {% for i in '12345' %}
                        <option value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <label>Комментарии</label><br>
                    <textarea name="content"></textarea>
                </div>
                <div>
                    <button>Оставить отзыв</button>
                </div>
            </form>
        {% endif %}

        {% for rev in product.reviews.all %}
            <div class="px-4 py-6 bg-gray-100 rounded-xl mb-4">
                <strong>Оценка: </strong>{{ rev.rating }}/ 5
                <br>
                <strong>Дата: </strong> {{ rev.created_at|date:'d-m-Y' }}
                <br>
                <strong>Комментарий: </strong>
                {{ rev.content }}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}