ecom_store/cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('success/', success, name='success'),
    path('checkout/', checkout, name='checkout'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('update_cart/<int:product_id>/<str:action>/', update_cart, name='update_cart'),
    path('hx_menu_cart/', hx_menu_cart, name='hx_menu_cart'),
    path('hx_cart_total/', hx_cart_total, name='hx_cart_total'),
]

ecom_store/core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from product.views import *
from .views import *

app_name = 'core'

urlpatterns = [
    path('', frontpage, name='frontpage'),
    #user auth
    path('signup/', signup, name='signup'),
    path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', logout_user, name='logout'),
    #account
    path('myaccount/', myaccount, name='myaccount'),
    path('myaccount/edit/', edit_myaccount, name='edit_myaccount'),
    #shop
    path('shop/', shop, name='shop'),
    path('shop/<slug:slug>', product, name='product'),
    
]

ecom_store/ecom_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #cores
    path('', include('core.urls')),
    #cart
    path('cart/', include('cart.urls')),
    #order
    path('order/', include('order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom_store/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, required=True, label='Имя')
    last_name = forms.CharField(max_length=50, required=True, label='Фамилия')
    email = forms.EmailField(max_length=255, required=True, label='Электронная почта')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        labels = {
            'username': 'Имя пользователя',
            'password1': 'Пароль',
            'password2': 'Повтор пароля',
        }
        
    def clean_email(self):
        """Reject email that differ only in case."""
        email = self.cleaned_data.get("email")
        if (
            email
            and self._meta.model.objects.filter(email=email).exists()
        ):
            self._update_errors(
                ValidationError(
                    {
                        "email": self.instance.unique_error_message(
                            self._meta.model, ["email"]
                        )
                    }
                )
            )
        else:
            return email
        

ecom_store/core/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from product.models import Product, Category
from .forms import SignUpForm


def frontpage(request):
    products = Product.objects.all()[:8]
    return render(request, 'core/frontpage.html', {'products': products})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'core/signup.html', {'form': form})

def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('/')

@login_required
def myaccount(request):
    return render(request, 'core/myaccount.html')

@login_required
def edit_myaccount(request):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        user.save()
        return redirect('core:myaccount')

    return render(request, 'core/edit_myaccount.html')


def shop(request):
    categories = Category.objects.all()
    products = Product.objects.all()

    #Активная категория
    active_cat = request.GET.get('category', '')
    if active_cat:
        products = products.filter(category__slug=active_cat)

    #Поиск
    query = request.GET.get('query', '')
    if query:
        products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))

    context = {
        'categories': categories,
        'products': products,
        'active_cat': active_cat,
    }
    return render(request, 'core/shop.html', context=context)

ecom_store/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}Мебель Поволжья{% endblock %}</title>
</head>
<body>
    <nav class="border-b border-gray-300">
        <div class="max-w-6xl mx-auto py-2 px-6 xl:px-0 flex items-center justify-between">
            <div class="menu-left flex items-center space-x-6">
                <a href="/" class="py-4 text-lg text-purple-500 font-semibold">Главная</a>
                <ul class="flex items-center space-x-4">
                    <li><a href="{% url 'core:shop' %}">Товары</a></li>
                    <li><a href="">О нас</a></li>
                </ul>
            </div>
            <div class="menu-right flex items-center space-x-4">
                {% if user.is_authenticated %}
                    <a href="{% url 'core:myaccount' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                        </svg>                      
                    </a>
                    <a href="{% url 'core:logout' %}">Выйти</a>
                {% else %}
                    <a href="{% url 'core:signup' %}">Регистрация</a>
                    <a href="{% url 'core:login' %}">Войти</a>
                {% endif %}

                <div 
                    hx-get="{% url 'cart:hx_menu_cart' %}"
                    hx-trigger="update-menu-cart from:body"
                    hx-swap="innerHTML">

                    {% include 'cart/partials/menu_cart.html' %}
                </div>
            </div>
        </div>
    </nav>
    <main>
        {% block content %}
        {% endblock%}
    </main>
    <footer class="bg-gray-100">
        <div class="max-w-6xl mx-auto py-10 px-6 xl:px-0 md:flex justify-between">
            <div class="footer-left mb-12 md:mb-0">
                <h2 class="mb-5 uppercase text-lg">О нас</h2>
                <p class="text-gray-700"> Информация о нашем магазине</p>
            </div>
            <div class="footer-right">
                <h2 class="mb-5 uppercase text-lg">Наши ссылки</h2>
                <ul class="space-y-2">
                    <li><a href="" class="text-purple-500 hover:text-purple-800">Facebook</a></li>
                    <li><a href="" class="text-purple-500 hover:text-purple-800">Instagram</a></li>
                    <li><a href="" class="text-purple-500 hover:text-purple-800">X</a></li>
                    
                </ul>
            </div>
        </div>
    </footer>
    <script src="https://unpkg.com/htmx.org@1.7.0"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

ecom_store/templates/core/edit_myaccount.html
{% extends 'core/base.html' %}

{% block title %}Редактирование профиля{% endblock %}

{% block content %}

<div class="max-w-6xl mx-auto p-6">
    <h1 class="mb-5 text-3xl">Редактирование профиля</h1>

    <form method="post" class="space-y-3">
        {% csrf_token %}
        <div>
            <label>Имя</label>
            <input name="first_name" value="{{ request.user.first_name }}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <label>Фамилия</label>
            <input name="last_name" value="{{ request.user.last_name }}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <label>Имя пользователя</label>
            <input name="username" value="{{ request.user.username }}" type="text" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <label>Электронная почта</label>
            <input name="email" value="{{ request.user.email }}" type="email" class="w-full mt-2 py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <button class="py-4 px-6 rounded-xl text-white bg-purple-500">Изменить</button>
        </div>
    </form>
</div>

{% endblock %}

ecom_store/templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block title %}Мебель Поволжья{% endblock %}

{% block content %}
<header class="px-6 py-10 lg:py-20 bg-purple-500">
    <div class="max-w-3xl mx-auto text-center">
        <p class="mb-2 text-3xl lg:text-5xl text-white">Мебель Поволжья</p>

        <p class="mb-10 text-white">Мебель для любой из ваших комнат</p>

        <a href="{% url 'core:shop' %}" class="inline-block px-8 py-4 rounded-xl bg-white text-purple-500 hover:bg-gray-200">К покупкам</a>
    </div>
</header>

<div class="max-w-6xl mx-auto py-2 px-6 xl:px-0">
    <div class="products flex items-center flex-wrap">
        {% for product in products %}
            {% include 'product/partials/product_list.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

ecom_store/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}

<div class="max-w-lg mx-auto flex flex-wrap p-6">
    <div class="w-full bg-gray-100 p-6 rounded-xl">
        <h1 class="mb-6 text-2xl">Вход</h1>
        
        <form method="post" class="space-y-3">
            {% csrf_token %}
            
            <div>
                <label>Имя пользователя или электронная почта</label>
                <input type="text" name="username" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
            </div>
            
            <div>
                <label>Пароль</label>
                <input type="password" name="password" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
            </div>

            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                            <p>{{ field.label }} - {{ error|escape }}</p>
                        </div>
                    {% endfor %}
                {% endfor %}
            {% endif %}

            <div>
                <button type="submit" class="py-4 px-6 rounded-xl text-white bg-purple-500 hover:bg-purple-700">
                    Войти
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

ecom_store/templates/core/myaccount.html
{% extends 'core/base.html' %}

{% block title %}Профиль - мебель поволжья{% endblock %}

{% block content %}

<div class="max-w-6xl mx-auto p-6">
    <h1 class="mb-5 text-3xl">Мой профиль</h1>

    <div class="mb-6">
        <strong>Имя: </strong> {{ request.user.get_full_name }}<br>
        <strong>Имя пользователя: </strong> {{ request.user.username }}<br>
        <strong>Электронная почта: </strong> {{ request.user.email }}<br><br>

        <a href="{% url 'core:edit_myaccount' %}" class="inline-block py-2 px-6 rounded-xl text-white bg-purple-500">Редактировать</a>
    </div>
    <hr>

    <h2 class="my-6 text-xl">Мои заказы</h2>
    {% for order in request.user.orders.all %}
        <div class="w-full mb-6 p-6 flex flex-wrap bg-gray-100 rounded-xll">
            <div class="mb-6 flex justify-between">
                <a href="">Номер заказа: {{ order.id }}</a>
            </div>

            <div class="mb-6 w-full">
                {% for item in order.items.all %}
                    <div class="product mb-6 flex pr-6">
                        <a href="{% url 'core:product' item.product.slug %}" class="w-1/4">
                            <img class="hover:shadow-lg rounded-xl" src="{{ item.product.get_thumbnail }}">
                        </a>

                        <div class="w-3/4 pl-6">
                            <div class="flex justify-between">
                                <a href="{% url 'core:product' item.product.slug %}" class="text-lg">Название товара: {{ item.product.name }}</a>
                                <p class="mb-6 pt-1 text-gray-400">Цена: {{ item.get_total_price }} руб.</p>
                            </div>
                            <hr>

                            <div class="mt-6">
                                Кол-во: {{ item.quantity }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div>
                <p class="text-lg">Дата заказа: {{ order.created_at }}</p>
                <p class="text-lg">Итого: {{ order.get_total_price }} руб.</p>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

ecom_store/templates/core/shop.html
{% extends 'core/base.html' %}

{% block title %}Каталог{% endblock %}

{% block content %}

<div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
    <div class="filters w-full lg:w-1/4">
        <h3 class="mb-3 text-xl text-uppercase">Поиск</h3>
        <form method="get" action=".">
            {% csrf_token %}
            <div class="flex">
                <input type="text" name="query" class="p-4 bg-gray-100 border-0" placeholder="Поиск...">
                <button class="p-4 bg-gray-100 border-0">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
                    </svg>                      
                </button>
            </div>
        </form>
        <h3 class="mt-6 mb-3 text-xl text-uppercase">Категории</h3>

        <ul class="space-y-2">
            <li><a href="{% url 'core:shop' %}" class="{% if not active_cat %} text-purple-500 {% else %} text-gray-500 {% endif %}">Все категории</a></li>
            {% for cat in categories %}
                <li><a href="{% url 'core:shop' %}?category={{ cat.slug }}" class="{% if cat.slug == active_cat %} text-purple-500 {% else %} text-gray-500 {% endif %}">{{ cat.name }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <div class="products w-full lg:w-3/4 -mt-4 flex items-center flex-wrap">
        {% for product in products %}
            {% include 'product/partials/product_list.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

ecom_store/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}

<div class="max-w-lg mx-auto flex flex-wrap p-6">
    <div class="w-full bg-gray-100 p-6 rounded-xl">
        <h1 class="mb-6 text-2xl">Регистрация</h1>
        
        <form method="post" class="space-y-3">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div>
                <label>Имя пользователя</label>
                <input type="text" name="username" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
            </div>

            <div>
                <label>Имя</label>
                <input type="text" name="first_name" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
            </div>

            <div>
                <label>Фамилия</label>
                <input type="text" name="last_name" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
            </div>

            <div>
                <label>Электронная почта</label>
                <input type="email" name="email" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
            </div>

            <div>
                <label>Пароль</label>
                <input type="password" name="password1" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
            </div>

            <div>
                <label>Повтор пароля</label>
                <input type="password" name="password2" class="w-full mt-2 py-4 px-6 bg-white rounded-xl">
            </div>

            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                            <p>{{ field.label }} - {{ error|escape }}</p>
                        </div>
                    {% endfor %}
                {% endfor %}
            {% endif %}
            
            <div>
                <button type="submit" class="py-4 px-6 rounded-xl text-white bg-purple-500 hover:bg-purple-700">Регистрация</button>
            </div>
            
        </form>
    </div>
</div>
{% endblock %}