ecom_store/cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('success/', success, name='success'),
    path('checkout/', checkout, name='checkout'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('update_cart/<int:product_id>/<str:action>/', update_cart, name='update_cart'),
    path('hx_menu_cart/', hx_menu_cart, name='hx_menu_cart'),
    path('hx_cart_total/', hx_cart_total, name='hx_cart_total'),
]

ecom_store/core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from product.views import *
from .views import *

app_name = 'core'

urlpatterns = [
    path('', frontpage, name='frontpage'),
    #user auth
    path('signup/', signup, name='signup'),
    path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', logout_user, name='logout'),
    #account
    path('myaccount/', myaccount, name='myaccount'),
    path('myaccount/edit/', edit_myaccount, name='edit_myaccount'),
    #shop
    path('shop/', shop, name='shop'),
    path('shop/<slug:slug>', product, name='product'),
    
]

ecom_store/ecom_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #cores
    path('', include('core.urls')),
    #cart
    path('cart/', include('cart.urls')),
    #order
    path('order/', include('order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom_store/cart/models.py
from django.db import models

# Create your models here.

ecom_store/cart/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .cart import Cart
from order.models import Order, OrderItem
from product.models import Product

def add_to_cart(request, product_id):
    cart = Cart(request)
    cart.add(product_id)
    return render(request, 'cart/partials/menu_cart.html')

def cart(request):
    return render(request, 'cart/cart.html')

def success(request):
    cart = Cart(request)
    cart.clear()
    return render(request, 'cart/success.html')

def update_cart(request, product_id, action):
    cart = Cart(request)

    if action == 'increment':
        cart.add(product_id, 1, True)
    else:
        cart.add(product_id, -1, True)

    product = Product.objects.get(pk=product_id)
    quantity = cart.get_item(product_id) 

    if quantity:
        quantity = quantity['quantity']
        item = {
            'product': {
                'id': product.pk,
                'name': product.name,
                'image': product.image,
                'get_thumbnail': product.get_thumbnail(),
                'price': product.price,
                'slug': product.slug
            },
            'total_price': (quantity * product.price),
            'quantity': quantity,
        }
    else:
        item = None
    response = render(request, 'cart/partials/cart_item.html', {'item': item})
    response['HX-Trigger'] = 'update-menu-cart'
    return response

@login_required
def checkout(request):
    pub_key = settings.STRIPE_API_KEY_PUBLISHABLE
    return render(request, 'cart/checkout.html', {'pub_key': pub_key})

def hx_menu_cart(request):
    return render(request, 'cart/partials/menu_cart.html')

def hx_cart_total(request):
    return render(request, 'cart/partials/cart_total.html')

ecom_store/templates/cart/cart.html
{% extends 'core/base.html' %}

{% block title %}Корзина - Мебель Повольжья{% endblock %}

{% block content %}

<div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
    <div class="product w-full lg:w-3/4">
        {% for item in cart %}
            {% include 'cart/partials/cart_item.html' %}
        {% endfor %}
    </div> 

    <div class="summary w-full md:w-1/4 p-6 bg-gray-100 rounded-xl mt-3">
        <h2 class="uppercase text-lg mb-5">Подтвержение</h2>

        <div class="mb-6 flex justify-between">
            <span class="font-semibold">Всего:</span>
            <span
                hx-get="{% url 'cart:hx_cart_total' %}"
                hx-trigger="update-menu-cart from:body"
                hx-swap="innerHTML">
                {% include 'cart/partials/cart_total.html' %}
            </span>
        </div>
    <br>
    {% if not cart %}
        <a href="{% url 'core:shop' %}" class="inline-block px-4 py-3 rounded-xl bg-purple-500 hover:bg-purple-700 text-white">
            Смотреть товары
        </a>
    {% else %}
        <a href="{% url 'cart:checkout' %}" class="inline-block px-4 py-3 rounded-xl bg-purple-500 hover:bg-purple-700 text-white">
            Перейти к оформлению
        </a>
    {% endif %}
    </div>
</div>
{% endblock %}

ecom_store/templates/cart/checkout.html
{% extends 'core/base.html' %}

{% block title %}Оформление заказа{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
    <div class="product w-full lg:w-3/4">
        <h1 class="mb-5 text-3xl">Оформление заказа</h1>
        <p class="text-gray-400">
            Данные нужны для курьера и сообщений об изменениях статуса вашего заказа
        </p>
        <div class="w-full  md:pr-6">
            <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                <h2 class="mb-5 text-uppercase text-lg">Получатель</h2>

                <div class="flex space-x-6">
                    <div class="w-1/2 mb-4">
                        <label class="inline-block mb-2">Имя</label>
                        <input name="first_name" type="text" class="w-full p-5 rounded-xl" value="{{ request.user.first_name }}">
                    </div>

                    <div class="w-1/2 mb-4">
                        <label class="inline-block mb-2">Фамилия</label>
                        <input name="last_name" type="text" class="w-full p-5 rounded-xl" value="{{ request.user.last_name }}">
                    </div>
                </div>

                <div class="mb-4">
                    <label class="inline-block mb-2">Адрес доставки</label>
                    <input name="address" type="text" class="w-full p-5 rounded-xl">
                </div>

                <div class="flex space-x-6">
                    <div class="w-1/2 mb-4">
                        <label class="inline-block mb-2">Почтовый индекс</label>
                        <input name="zipcode" type="text" class="w-full p-5 rounded-xl">
                    </div>

                    <div class="w-1/2 mb-4">
                        <label class="inline-block mb-2">Область</label>
                        <input name="place" type="text" class="w-full p-5 rounded-xl">
                    </div>
                </div>
            </div>

            <div class="mb-6 p-6 bg-gray-100 rounded-xl">
                <h2 class="mb-5 text-uppercase text-lg">Контактная информация</h2>

                <div class="mb-4">
                    <label class="inline-block mb-2">Электронная почта</label>
                    <input name="email" type="email" class="w-full p-5 rounded-xl" value="{{ request.user.email }}">
                </div>

                <div class="mb-4">
                    <label class="inline-block mb-2">Номер телефона</label>
                    <input name="phone" type="phone" class="w-full p-5 rounded-xl">
                </div>
            </div>

            <div class="mb-6 p-6 bg-gray-100 rounded-xl" id="errors">
                
            </div>
        </div>
    </div>
    <div class="summary w-full md:w-1/4 p-6 bg-gray-100 rounded-xl mt-3">
        <h1 class="uppercase text-lg mb-5">Ваш заказ</h1>

        <div class="mb-6 flex justify-between">
            <span class="font-semibold">Всего:</span>
            <span>{{ cart.get_total_cost }} руб</span>
        </div>
    <br>
    <button 
        onclick="buy(event)"
        class="inline-block px-8 py-3 rounded-xl bg-purple-500 hover:bg-purple-700 text-white">
        Оформить заказ
    </button>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script type="application/javascript" src="https://js.stripe.com/v3/"></script>
    <script>
        let el = document.querySelector('#errors')
        function validateForm(data) {
            let errors = []

            if (data.first_name === '') {
                errors.push('Поле имя пустое')
            }

            if (data.last_name === '') {
                errors.push('Поле фамилия пустое')
            }

            if (data.email === '') {
                errors.push('Поле электронная почта пустое')
            }

            if (data.phone === '') {
                errors.push('Поле телефон пустое')
            }

            if (data.address === '') {
                errors.push('Поле адрес пустое')
            }

            if (data.zipcode === '') {
                errors.push('Поле почтовый индекс пустое')
            }

            if (data.place === '') {
                errors.push('Поле область пустое')
            }

            if (errors.length > 0) {
                let html = '<ul>';

                errors.forEach((error) => {
                    html += '<li style="color:red">' + error + '</li>';
                    })
                
                el.innerHTML = html + '</ul>'; 
                
                window.scrollTo({
                    top: 1000,  // это координат где должен быть экран
                    behavior: 'smooth'  //Это анимация
                })       
                
            } else {
                el.innerHTML = ''
            } 
            
            return errors
        }
        function buy(event) {
            event.preventDefault()

            let data = {
                'first_name': document.querySelector('input[name=first_name]').value,
                'last_name': document.querySelector('input[name=last_name]').value,
                'email': document.querySelector('input[name=email]').value,
                'phone': document.querySelector('input[name=phone]').value,
                'address': document.querySelector('input[name=address]').value,
                'zipcode': document.querySelector('input[name=zipcode]').value,
                'place': document.querySelector('input[name=place]').value,
            }

            let errors = validateForm(data)
            if (errors.length) {
                console.log('Errors', errors)
            }
            else {
                var stripe = Stripe('{{ pub_key }}')
                fetch('/order/start_order/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                    credentials: 'same-origin',
                    body: JSON.stringify(data)
                }).then(function(response) {
                    return response.json()
                }).then(function(session) {
                    return stripe.redirectToCheckout({ sessionId: session.session.id })
                }).then(function(result){
                    if (result.error) {
                        alert(result.error.message)
                    }
                }).catch(function(error) {
                    console.log('Errors', error)
                }) 
            }
            return false
        }
    </script>
{% endblock %}

ecom_store/templates/cart/success.html
{% extends 'core/base.html' %}

{% block title %}Успешно{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto flex flex-wrap items-start py-6 px-6 xl:px-0">
    <div class="product w-full lg:w-3/4">
        <h1 class="mb-5 text-3xl">Успешно</h1>
        <p>Спасибо за покупку!</p>
        <br>
        <p>Чтобы уточнить информацию по вашему заказу вы можете обратиться по номеру <strong>89275552211</strong></p>
        <p>Или по электронной почте <strong>root@mail.ru</strong></p>
    </div>
{% endblock %}