ecom_store/cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('success/', success, name='success'),
    path('checkout/', checkout, name='checkout'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('update_cart/<int:product_id>/<str:action>/', update_cart, name='update_cart'),
    path('hx_menu_cart/', hx_menu_cart, name='hx_menu_cart'),
    path('hx_cart_total/', hx_cart_total, name='hx_cart_total'),
]

ecom_store/core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from product.views import *
from .views import *

app_name = 'core'

urlpatterns = [
    path('', frontpage, name='frontpage'),
    #user auth
    path('signup/', signup, name='signup'),
    path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', logout_user, name='logout'),
    #account
    path('myaccount/', myaccount, name='myaccount'),
    path('myaccount/edit/', edit_myaccount, name='edit_myaccount'),
    #shop
    path('shop/', shop, name='shop'),
    path('shop/<slug:slug>', product, name='product'),
    
]

ecom_store/ecom_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #cores
    path('', include('core.urls')),
    #cart
    path('cart/', include('cart.urls')),
    #order
    path('order/', include('order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom_store/cart/models.py
from django.db import models

# Create your models here.

ecom_store/cart/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .cart import Cart
from order.models import Order, OrderItem
from product.models import Product

def add_to_cart(request, product_id):
    cart = Cart(request)
    cart.add(product_id)
    return render(request, 'cart/partials/menu_cart.html')

def cart(request):
    return render(request, 'cart/cart.html')

def success(request):
    cart = Cart(request)
    cart.clear()
    return render(request, 'cart/success.html')

def update_cart(request, product_id, action):
    cart = Cart(request)

    if action == 'increment':
        cart.add(product_id, 1, True)
    else:
        cart.add(product_id, -1, True)

    product = Product.objects.get(pk=product_id)
    quantity = cart.get_item(product_id) 

    if quantity:
        quantity = quantity['quantity']
        item = {
            'product': {
                'id': product.pk,
                'name': product.name,
                'image': product.image,
                'get_thumbnail': product.get_thumbnail(),
                'price': product.price,
                'slug': product.slug
            },
            'total_price': (quantity * product.price),
            'quantity': quantity,
        }
    else:
        item = None
    response = render(request, 'cart/partials/cart_item.html', {'item': item})
    response['HX-Trigger'] = 'update-menu-cart'
    return response

@login_required
def checkout(request):
    pub_key = settings.STRIPE_API_KEY_PUBLISHABLE
    return render(request, 'cart/checkout.html', {'pub_key': pub_key})

def hx_menu_cart(request):
    return render(request, 'cart/partials/menu_cart.html')

def hx_cart_total(request):
    return render(request, 'cart/partials/cart_total.html')

ecom_store/templates/cart/partials/cart_item.html
{% if item %}
<div class="product mb-6 flex pr-6" id="cart-item-{{ item.product.id }}">
    <a href="{% url 'core:product' item.product.slug %}" class="w-1/4">
        <img class="hover:shadow-lg rounded-xl" src="{{ item.product.get_thumbnail }}">
    </a>

    <div class="w-3/4 pl-6">
        <div class="flex justify-between">
            <a href="{% url 'core:product' item.product.slug %}" class="text-lg">{{ item.product.name }}</a>
            <span class="mb-6 pt-1 text-black">Цена: {{ item.total_price }} руб.</span>
        </div>
        <hr>

        <div class="quantity mt-6 flex items-center space-x-4">
            <a style="cursor: pointer;"
                class="p-3 bg-gray-100"
                hx-get="{% url 'cart:update_cart' item.product.id 'decrement' %}"
                hx-target="#cart-item-{{ item.product.id }}"
                hx-swap="outerHTML"
                >-
            </a>
            <span>{{ item.quantity }}</span>
            <a style="cursor: pointer;"
                class="p-3 bg-gray-100"
                hx-get="{% url 'cart:update_cart' item.product.id 'increment' %}"
                hx-target="#cart-item-{{ item.product.id }}"
                hx-swap="outerHTML"
                >+
            </a>
        </div>
    </div>
</div>
{% endif %}

ecom_store/templates/cart/partials/cart_total.html
{{ cart.get_total_cost }} руб.

ecom_store/templates/cart/partials/menu_cart.html
<a href="{% url 'cart:cart' %}" id="menu-cart-button" class="relative">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
        <path fill-rule="evenodd" d="M7.5 6v.75H5.513c-.96 0-1.764.724-1.865 1.679l-1.263 12A1.875 1.875 0 004.25 22.5h15.5a1.875 1.875 0 001.865-2.071l-1.263-12a1.875 1.875 0 00-1.865-1.679H16.5V6a4.5 4.5 0 10-9 0zM12 3a3 3 0 00-3 3v.75h6V6a3 3 0 00-3-3zm-3 8.25a3 3 0 106 0v-.75a.75.75 0 011.5 0v.75a4.5 4.5 0 11-9 0v-.75a.75.75 0 011.5 0v.75z" clip-rule="evenodd" />
    </svg>  

    <span class="p-1 absolute -top-11 -right-8 bg-indigo-500 text-white rounded-full">{{ cart|length }}</span>
</a>